T4. Случайная величина распределена равномерно на отрезке [θ, 2θ]

а) По выборке объема n найти оценки параметра θ методом моментов и методом максимального правдоподобия  
б) проверить на несмещенность и состоятельность, при необходимости исправить оценки

![omm](omm.jpg)

![omm_checks](OMM_checks.jpg)

![OMP_checks](OMP_CHECKS.JPG)

![OMP_CHECKS2](OMP_CHECKS2.JPG)

![OMP_CHECKS3](OMP_CHECKS3.JPG)

![OMP_CHECKS4](OMP_CHECKS4.JPG)

c) Сравнить ассимптотическую эффективность оценок

![effect_compare](compare_effect.jpg)

d) Построить точный доверительный интервал для параметра 

![INTERVAL_ACCURATE](INTERVAL_ACCURATE.jpg)

e) Построить асимптотический доверительный интервал для параметра

In [37]:
#Примечание: на лекции были даны значения квантилей для стандартного нормального распределения
# и доверительной вероятности 0.95

![assimpt_1](assimpt1.jpg)

![assimpt](assimpt2.jpg)

f) Сгенерируйте выборку объема n=100 для некоторого значения параметра. Вычислите указанные выше доверит.интервалы для вероятности 0.95

In [25]:
teta = 10 #некоторое значение параметра
beta = 0.95 #доверительная вероятность
n = 100 #объем выборки

In [26]:
import numpy as np

In [27]:
X = np.random.uniform(teta, 2*teta, n)

In [28]:
X

array([13.43519189, 11.6549283 , 18.39872735, 11.36956962, 13.47403716,
       16.6679622 , 17.34544497, 12.9074573 , 18.62033352, 14.19588706,
       13.97794214, 13.01383309, 17.37181766, 18.93851441, 12.35968745,
       16.67108122, 17.47162233, 17.49995515, 10.73960094, 13.39629265,
       15.51475322, 15.97078506, 15.56182737, 17.33776565, 14.14496395,
       11.63357416, 16.78713988, 19.71898241, 16.64411787, 19.15712135,
       19.42165389, 12.80042864, 11.52935154, 12.66974864, 19.7490567 ,
       16.98105562, 18.10699955, 12.67188483, 11.70468425, 17.36549654,
       12.25442513, 18.07830742, 16.78255232, 19.98814852, 12.56468363,
       12.05550283, 11.14241422, 17.31410443, 12.60809066, 15.61537448,
       15.30839944, 18.4774992 , 17.58165605, 14.62784973, 13.28031647,
       14.34018485, 17.69054024, 10.52874977, 17.96670055, 18.4324731 ,
       11.99425063, 16.38918209, 11.71291524, 19.00582377, 19.55552226,
       12.36109235, 13.1028291 , 17.63892569, 15.15490864, 14.06

In [33]:
accurate_interval = (X.max() / ((((1+beta)/2)**(1/n))+1), X.max() / ((((1-beta)/2)**(1/n))+1))

In [34]:
accurate_interval # ЭТО ТОЧНЫЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ

(9.99533939952149, 10.17838803480276)

In [35]:
assympt_interval = (2/3*X.mean() - 2.94*(((X**2).mean() - (X.mean())**2)/n)**(1/2), 
                    2/3*X.mean() + 2.94*(((X**2).mean() - (X.mean())**2)/n)**(1/2))

In [36]:
assympt_interval #ЭТО АССИМПТОТИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ

(9.139105025166117, 10.805760723729634)




BOOTSTRAP

In [88]:
teta_ = 2/3*X.mean() #оценка параметра
N = 50000 #мощность бутстрапа

In [89]:
XX = []
for _ in range(N):
    XX.append(np.random.uniform(teta_, 2*teta_, n))
XX = np.array(XX)

In [90]:
XX #массив выборок по вероятностной модели с параметром - нашей оценкой (смещенной омп)

array([[15.39520106, 13.33302563, 14.03254355, ..., 19.3167768 ,
        17.36477842, 17.60794928],
       [18.98714728, 17.34896451, 18.40665664, ..., 13.34659503,
        15.99942031, 15.97035456],
       [15.42273263, 10.29991762, 14.82353969, ..., 15.60286597,
        11.90874042, 18.87164688],
       ...,
       [10.35615287, 17.77664352, 18.27390667, ..., 18.33064592,
        16.66397086, 15.83935093],
       [10.63969157, 14.35347634, 15.41247529, ..., 12.45903514,
        18.60650093, 12.32079196],
       [10.94116816, 11.03069079, 11.73442503, ..., 16.41045879,
        16.16131849, 19.07674341]])

In [91]:
teta_X = np.apply_along_axis(lambda x: (2/3)*x.mean(), axis=1, arr=XX)

In [92]:
teta_X #оценки для каждой из 50000 подвыборок

array([ 9.84851054, 10.03000739, 10.10943038, ...,  9.80932135,
       10.09952777,  9.79467914])

In [93]:
teta_X.sort()
teta_X #вариационный ряд

array([ 9.07295686,  9.13675539,  9.23658328, ..., 10.69077716,
       10.74587284, 10.76045801])

In [94]:
teta_K1 = teta_X[int(N*((1-beta)/2))]
teta_K2 = teta_X[int(N*((1+beta)/2))]
print(teta_K1, teta_K2) #ЭТО ЧИСЛЕННЫЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ

9.59460761354774 10.351549830261533





СРАВНЕНИЕ ВСЕХ ИНТЕРВАЛОВ

In [95]:
l_accurate = accurate_interval[1] - accurate_interval[0]
print("ДЛИНА ТОЧНОГО ИНТЕРВАЛА:", l_accurate)

ДЛИНА ТОЧНОГО ИНТЕРВАЛА: 0.18304863528127058


In [96]:
l_assympt = assympt_interval[1] - assympt_interval[0]
print("ДЛИНА АССИМПТОТИЧЕСКОГО ИНТЕРВАЛА:", l_assympt)

ДЛИНА АССИМПТОТИЧЕСКОГО ИНТЕРВАЛА: 1.6666556985635168


In [86]:
print("ДЛИНА ЧИСЛЕННОГО ИНТЕРВАЛА:", teta_K2-teta_K1)

ДЛИНА ЧИСЛЕННОГО ИНТЕРВАЛА: 0.18271603407377235







T5

a) По выборке объема n найти оценку параметра методом максимального правдоподобия

![t5omp](t5omp.jpg)

b) Построить доверительный интервал для медианы

![median_interval_1](medianinterval1.jpg)

![median_interval_2](medianinterval2.jpg)

![medianinterval3](medianinterval3.jpg)

c) Построить асимптотический доверительный интервал для параметра

![assimpt3](assimpt3.jpg)

![assimpt4](assimpt4.jpg)

d) Сгенерируйте выборку объема n=100 для некоторого значения параметра. Вычислите указанные выше доверительные интервалы для доыерительной вероятности 0.95

In [247]:
teta = 5 #некоторое значение параметра
beta = 0.95 #доверительная вероятность
n = 100 #объем выборки

ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ МЕДИАНЫ

Моделирование случайной величины

![model_slvel](modelirovanie_slvel.jpg)

In [248]:
etta = np.random.uniform(0, 1, n)

In [249]:
X = (1-etta)**(1/(1-teta)) 

In [250]:
X

array([1.08018028, 1.16298454, 1.0388615 , 1.67583223, 1.02157156,
       1.12750572, 1.02763804, 1.47010423, 2.1297287 , 1.00534477,
       1.32371667, 1.19305535, 1.85210256, 1.40652351, 1.08418248,
       2.03944535, 1.0737241 , 1.13812425, 1.03157785, 1.06685242,
       1.02653798, 1.33975291, 1.25899841, 1.04414276, 1.18448107,
       1.00845818, 1.04697477, 1.02659817, 3.210731  , 1.03391028,
       1.28449604, 1.02580476, 1.98764467, 1.88213447, 1.02820037,
       1.08800297, 1.00379003, 1.29471755, 1.54299168, 1.44368736,
       1.11529759, 1.05722442, 1.03039237, 1.48771053, 1.3555993 ,
       1.02751923, 1.33331934, 1.24118462, 2.0469006 , 1.20754771,
       1.51649032, 1.43685991, 1.14374897, 1.01156113, 1.67153887,
       1.27516053, 1.78721457, 1.10370332, 1.05148245, 1.54944607,
       1.01576187, 1.03648975, 1.16547685, 1.21574493, 1.07900914,
       1.20858583, 1.31126675, 1.17976654, 1.05856967, 1.55867263,
       1.05003665, 1.03066784, 1.55230096, 1.40896619, 1.08293

In [251]:
teta_ = n / (np.sum(np.log(X))) + 1

In [252]:
teta_

5.12638855817024

In [253]:
median_interval = ((-1.96 * (2**(1/(teta_-1))*np.log(2)) / ((teta_-1)* n**(1/2))) + 2**(1/(teta_-1)),
                   (1.96 * (2**(1/(teta_-1))*np.log(2)) / ((teta_-1)* n**(1/2))) + 2**(1/(teta_-1)))

In [254]:
median_interval

(1.143965842477163, 1.221858015322525)

ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ ДЛЯ ПАРАМЕТРА

In [255]:
teta_interval = ((-1.96*((teta_-1)/(n**(1/2))) + teta_),
                 (1.96*((teta_-1)/(n**(1/2))) + teta_))

In [256]:
teta_interval

(4.317616400768873, 5.935160715571607)

t) Численно постройте бутстраповский доверительный интервал двумя способами, используя параметрический бутстрап и непараметрический бутстрап

НЕПАРАМЕТРИЧЕСКИЙ БУТСТРАП

In [257]:
N=50000 #мощность бутстрапа

In [258]:
XX = []
for _ in range(N):
    #генерируем подвыборку с повторениями по нашей выборке-вероятностной модели
    XX.append(np.random.choice(X, n, replace=True))
XX = np.array(XX)

In [259]:
XX

array([[1.27516053, 1.85210256, 1.06685242, ..., 2.0469006 , 1.54944607,
        1.12352145],
       [2.03249635, 1.28449604, 1.08293865, ..., 1.03391028, 1.00845818,
        1.02157156],
       [1.40652351, 1.16298454, 1.44958864, ..., 1.44958864, 1.20858583,
        1.16034196],
       ...,
       [3.210731  , 1.01576187, 1.18448107, ..., 1.00845818, 1.08293865,
        1.07632047],
       [1.08018028, 1.78721457, 1.13812425, ..., 1.54944607, 1.47010423,
        1.03066784],
       [1.20858583, 1.54944607, 1.16034196, ..., 1.02751923, 1.00845818,
        1.32371667]])

In [260]:
#считаем оценку параметра для каждой подвыборки
teta_X = np.apply_along_axis(lambda x: n / (np.sum(np.log(x))) + 1, axis=1, arr=XX)

In [261]:
teta_X.shape

(50000,)

In [262]:
teta_X

array([5.12643088, 5.51298193, 4.86397106, ..., 5.12049804, 5.25853136,
       5.42247367])

In [263]:
delta_X = teta_X - teta_

In [264]:
delta_X #отклонение оценок подвыборок от оценки "вероятностной модели"-главной выборки

array([ 4.23239862e-05,  3.86593369e-01, -2.62417501e-01, ...,
       -5.89051421e-03,  1.32142797e-01,  2.96085114e-01])

In [265]:
delta_X.sort()
delta_X #вариационный ряд

array([-1.19374012, -1.1613766 , -1.14411845, ...,  1.97812825,
        1.99439351,  2.23120757])

In [266]:
delta_K1 = delta_X[int(N*((1-beta)/2))]
delta_K2 = delta_X[int(N*((1+beta)/2))]

nonparametric_interval = (teta_ - delta_K2, teta_ - delta_K1)
nonparametric_interval

(4.250213672607167, 5.773929078161901)

ПАРАМЕТРИЧЕСКИЙ БУТСТРАП

In [267]:
#подставляем оценку в модель и генерируем выборки по модели с известным параметром
XXX = []
for _ in range(N):
    etta = np.random.uniform(0, 1, n)
    XXX.append((1-etta)**(1/(1-teta)) )
XXX = np.array(XXX)

In [268]:
XXX

array([[1.00618812, 1.15359461, 1.00306044, ..., 1.05740147, 1.02380353,
        1.09030486],
       [1.40342952, 1.26404804, 1.55510005, ..., 1.06595516, 1.17951852,
        1.29670332],
       [1.05415962, 1.17309517, 1.32633188, ..., 1.62109779, 1.08538787,
        1.77950463],
       ...,
       [1.25770354, 1.30603369, 1.34067192, ..., 1.06798581, 1.07894581,
        1.12174715],
       [1.00929654, 1.68522849, 1.12157046, ..., 1.18640692, 1.03244265,
        1.82096929],
       [1.0294117 , 1.54327391, 1.31933061, ..., 1.47959942, 1.07556123,
        1.06348507]])

In [269]:
#считаем оценку по каждой выборке
teta_X_p = np.apply_along_axis(lambda x: n / (np.sum(np.log(x))) + 1, axis=1, arr=XXX)

In [270]:
teta_X_p

array([5.15068153, 4.96807632, 4.51535128, ..., 5.19304988, 4.96736232,
       5.39512714])

In [271]:
#вариационный ряд
teta_X_p.sort()
teta_X_p

array([3.68876333, 3.70129319, 3.77387322, ..., 6.94843201, 6.97697338,
       7.20423004])

In [272]:
teta_K1_p = teta_X_p[int(N*((1-beta)/2))]
teta_K2_p = teta_X_p[int(N*((1+beta)/2))]

parametric_interval = (teta_K1_p, teta_K2_p)
parametric_interval 

(4.318732727021903, 5.916257647482173)

f) Сравнить все интервалы

In [273]:
print(f"АСИМПТОТИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ МЕДИАНЫ: ({median_interval[0]}, {median_interval[1]})")
print(f"Длина: {median_interval[1]-median_interval[0]}")

АСИМПТОТИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ МЕДИАНЫ: (1.143965842477163, 1.221858015322525)
Длина: 0.07789217284536187


In [274]:
print(f"АСИМПТОТИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ ПАРАМЕТРА: ({teta_interval[0]}, {teta_interval[1]})")
print(f"Длина: {teta_interval[1]-teta_interval[0]}")

АСИМПТОТИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ ПАРАМЕТРА: (4.317616400768873, 5.935160715571607)
Длина: 1.6175443148027338


In [275]:
print(f"БУТСТРАПОВСКИЙ НЕПАРАМЕТРИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ ПАРАМЕТРА: ({nonparametric_interval[0]}, {nonparametric_interval[1]})")
print(f"Длина: {nonparametric_interval[1]-nonparametric_interval[0]}")

БУТСТРАПОВСКИЙ НЕПАРАМЕТРИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ ПАРАМЕТРА: (4.250213672607167, 5.773929078161901)
Длина: 1.523715405554734


In [276]:
print(f"БУТСТРАПОВСКИЙ ПАРАМЕТРИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ ПАРАМЕТРА: ({parametric_interval[0]}, {parametric_interval[1]})")
print(f"Длина: {parametric_interval[1]-parametric_interval[0]}")

БУТСТРАПОВСКИЙ ПАРАМЕТРИЧЕСКИЙ ДОВЕРИТЕЛЬНЫЙ ИНТЕРВАЛ ПАРАМЕТРА: (4.318732727021903, 5.916257647482173)
Длина: 1.5975249204602697
